### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_skip_horizontal'

### ISSUE THREAD

**Issue by c1a1o1** [sangwoomo/instagan#1]
E:\Users\Raytine\Anaconda3\python.exe F:/humanpose/instagan-master/datasets/generate_mhp_dataset.py
trainA:   0%|          | 0/4000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "F:/humanpose/instagan-master/datasets/generate_mhp_dataset.py", line 122, in <module>
    main()
  File "F:/humanpose/instagan-master/datasets/generate_mhp_dataset.py", line 17, in main
    generate_ccp_dataset(args)
  File "F:/humanpose/instagan-master/datasets/generate_mhp_dataset.py", line 40, in generate_ccp_dataset
    generate_mhp_dataset(args, 'train', 'A', get_cat_id(args.cat1))
  File "F:/humanpose/instagan-master/datasets/generate_mhp_dataset.py", line 63, in generate_mhp_dataset
    if not args.no_skip_horizontal:
AttributeError: 'Namespace' object has no attribute 'no_skip_horizontal'

**Comment by sangwoomo** [comment]
Thanks! There was a mistake during code simplification. I added 'no_skip_horizontal' argument.

**Comment by c1a1o1** [comment]
Thank you very much!
