### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'loadSize'

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#12]
Hi, I want to train a pix2pix model, and run: python train.py --dataroot ./datasets/photos2pants_ccp --name photos2pants_ccp_pix2pix --model pix2pix

but the result:
----------------- Options ---------------
               batch_size: 1
                    beta1: 0.5
          checkpoints_dir: ./checkpoints
           continue_train: False
                 dataroot: ./datasets/photos2pants_ccp          [default: None]
             dataset_mode: aligned
                direction: AtoB
              display_env: main
             display_freq: 400
               display_id: 1
            display_ncols: 6
             display_port: 8097
           display_server: http://localhost
          display_winsize: 256
                    epoch: latest
              epoch_count: 1
                fineSizeH: 200
                fineSizeW: 200
                  gpu_ids: 0
                init_gain: 0.02
                init_type: normal
                 input_nc: 3
                  isTrain: True                                 [default: None]
                lambda_L1: 100.0
                loadSizeH: 220
                loadSizeW: 220
                load_iter: 0                                    [default: 0]
                       lr: 0.0002
           lr_decay_iters: 50
                lr_policy: lambda
         max_dataset_size: inf
                    model: pix2pix                              [default: insta_gan]
               n_layers_D: 3
                     name: photos2pants_ccp_pix2pix             [default: experiment_name]
                      ndf: 64
                     netD: set
                     netG: unet_256
                      ngf: 64
                    niter: 100
              niter_decay: 100
               no_dropout: False
                  no_flip: False
                  no_html: False
                 no_lsgan: True
                     norm: batch
              num_threads: 4
                output_nc: 3
                    phase: train
                pool_size: 0
               print_freq: 100
           resize_or_crop: resize_and_crop
             save_by_iter: False
          save_epoch_freq: 5
         save_latest_freq: 5000
           serial_batches: False
                   suffix:
         update_html_freq: 1000
                  verbose: False
----------------- End -------------------
dataset [AlignedDataset] was created
#training images = 604
initialize network with normal
initialize network with normal
model [Pix2PixModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 54.414 M
[Network D] Total number of parameters : 9.760 M
-----------------------------------------------
WARNING:root:Setting up a new session...
create web directory ./checkpoints\photos2pants_ccp_pix2pix\web...
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    for i, data in enumerate(dataset):
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\aligned_dataset.py", line 26, in __getitem__
    assert(self.opt.loadSize >= self.opt.fineSize)
AttributeError: 'Namespace' object has no attribute 'loadSize'

**Comment by hjwang-824** [comment]
I guess I can fix this now

**Comment by hjwang-824** [comment]
I uncommented the loadSize and fineSize in the base_option.py, and the error can be fix, but here comes another:
WARNING:root:Setting up a new session...
create web directory ./checkpoints\photos2pants_ccp_pix2pix\web...
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\pix2pix_model.py", line 103, in optimize_parameters
    self.backward_D()
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\pix2pix_model.py", line 72, in backward_D
    pred_fake = self.netD(fake_AB.detach())
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 555, in forward
    segs = inp[:, self.input_nc:, :, :]  # (B, CA, W, H)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

**Comment by sangwoomo** [comment]
Hi, thanks for the correction. I think I used the different version of `aligned_dataset.py` for my experiments (I used earlier version of CycleGAN code for my paper submission, and updated it with the latest (of then) version for code release). The problem here is that I changed `loadSize` to `loadSizeH` & `loadSizeW` (so as `cropSize`) as we use non-square images.
Can you try to give option `--dataset_mode unaligned --serial_batches`?

**Comment by sangwoomo** [comment]
You should modify your dataset, that `trainA` and `trainB` should have same number of images (hence you should keep only the first mask and remove others) and remove `_0.png` part to match the name of image and mask. Then I guess serial version of unaligned should behave as aligned.

**Comment by hjwang-824** [comment]
Thanks, I used CCP dataset, and put the photos that contain pants(302 in total) in it and put the pants masks in the trainB. And I comment the loadSize and fineSize again. After trying the option --dataset_mode unaligned --serial_batches, the Namespace error and the RuntimeError above were fixed. But here raise another error:
---------- Networks initialized -------------
[Network G] Total number of parameters : 54.414 M
[Network D] Total number of parameters : 9.760 M
-----------------------------------------------
WARNING:root:Setting up a new session...
create web directory ./checkpoints\photos2pants_ccp_pix2pix\web...
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\pix2pix_model.py", line 99, in optimize_parameters
    self.forward()
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\pix2pix_model.py", line 66, in forward
    self.fake_B = self.netG(self.real_A)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 392, in forward
    return self.model(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 446, in forward
    return self.model(x)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\models\networks.py", line 448, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\modules\batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\nn\functional.py", line 1191, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size [1, 512, 1, 1]

**Comment by hjwang-824** [comment]
It seems like a batch size problem.

**Comment by hjwang-824** [comment]
Hi, what's the G and D you used to train the pix2pix? I read the original pix2pix code, and find that the D contains basic, n_layers and pixel model and the G contains Unet128 and Unet256, while the G in your code contains only basic and set model. And the pix2pix.py in your code set netG as Unet_256, but your network.py didn't contain the Unet_256. I add Unet_256 in the network.py, and then raise the error above.

**Comment by sangwoomo** [comment]
Hi, I used ResNet (basic) generator and PatchGAN (basic) discriminator. I guess UNet would also work well, but you should modify `define_G` in `networks.py`. I didn't know that training pix2pix model takes this long time, sorry for not checking the compatibility. One easy way is to simply run the [original CycleGAN code](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix), using same size for height and width. You can resize the generated mask.

**Comment by hjwang-824** [comment]
I set both the G and D to basic model in your code，and debug for a while， it works. And it’s training now. Thank you for answering the questions with patience. Your code and your paper are cool!
