### ISSUE TITLE
How did you test your pix2pix model

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#13]

**Comment by hjwang-824** [comment]
I had train the pix2pix model in your code. Then I want to test the model, and run: python test.py --dataroot ./datasets/test_photo2pants_pix2pix --model pix2pix --name photos2pants_ccp_pix2pix --loadSizeH 240 --loadSizeW 160 --fineSizeH 240 --fineSizeW 160
But it didn't work since it raised the AttributeError again.
dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints\photos2pants_ccp_pix2pix\latest_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.383 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    for i, data in enumerate(dataset):
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\aligned_dataset.py", line 26, in __getitem__
    assert(self.opt.loadSize >= self.opt.fineSize)
AttributeError: 'Namespace' object has no attribute 'fineSize'

**Comment by hjwang-824** [comment]
Since you did't use fineSize and loadSize, I put the photos in the foIder testA and new another empty folder testB, and I choose the option --dataset_mode unaligned，and run：python test.py --dataroot ./datasets/test_photo2pants_pix2pix --model pix2pix --name photos2pants_ccp_pix2pix --loadSizeH 240 --loadSizeW 160 --fineSizeH 240 --fineSizeW 160 --dataset_mode unaligned. 

Then here raised another error. It seems the testB can't be empty. However, If I want to test the pix2pix model there is nothing I can put in the testB folder.


dataset [UnalignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints\photos2pants_ccp_pix2pix\latest_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.383 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    for i, data in enumerate(dataset):
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ZeroDivisionError: Traceback (most recent call last):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\unaligned_dataset.py", line 31, in __getitem__
    index_B = index % self.B_size
ZeroDivisionError: integer division or modulo by zero

**Comment by sangwoomo** [comment]
Yes both testA and testB should not be empty. Since I wanted to change the code minimally, I simply put garbage data in testB and run the model.
