### ISSUE TITLE
Output with shape doesn't match the broadcast shape

### ISSUE THREAD

**Issue by mrvlasyuk** [sangwoomo/instagan#19]
Hi, thanks for the project! I'm trying to replicate results, but have a problem following your instructions.

0. I've cloned the repo.
1. I've downloaded jeans2skirt dataset.
2. Trying to start learning

`python3 train.py --dataroot ./datasets/jeans2skirt_ccp --model insta_gan --name jeans2skirt_ccp_instagan --loadSizeH 330 --loadSizeW 220 --fineSizeH 300 --fineSizeW 200 --niter 400 --niter_decay 200`

I get the following error:
```create web directory ./checkpoints/jeans2skirt_ccp_instagan/web...
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    for i, data in enumerate(dataset):
  File "/home/ubuntu/pr/data/__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/pr/data/unaligned_seg_dataset.py", line 71, in __getitem__
    A_segs = self.read_segs(A_seg_path, seed)
  File "/home/ubuntu/pr/data/unaligned_seg_dataset.py", line 42, in read_segs
    seg = self.fixed_transform(seg, seed)
  File "/home/ubuntu/pr/data/unaligned_seg_dataset.py", line 34, in fixed_transform
    return self.transform(image)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 300, 200] doesn't match the broadcast shape [3, 300, 200]```

I suppose it is because mask images have only 1 channel. Can you help?

**Comment by sangwoomo** [comment]
Hi, I guess it is due to the incompatibility of `torchvision` library. Can you change `transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))` in `./data/base_dataset.py` to `transforms.Normalize((0.5,), (0.5,))`?

**Comment by mrvlasyuk** [comment]
It works now. Thank you!
