### ISSUE TITLE
TypeError: 'int' object does not support item assignment

### ISSUE THREAD

**Issue by c1a1o1** [sangwoomo/instagan#2]
/generate_coco_dataset.py   Motorcycle -> Bicycle

loading annotations into memory...
Done (t=11.53s)
creating index...
index created!
trainA:   0%|          | 44/118287 [00:03<2:00:02, 16.42it/s]Traceback (most recent call last):
  File "/home/caocao/instagan-master/datasets/generate_coco_dataset.py", line 96, in <module>
    main()
  File "/home/caocao/instagan-master/datasets/generate_coco_dataset.py", line 15, in main
    generate_coco_dataset(args)
  File "/home/caocao/instagan-master/datasets/generate_coco_dataset.py", line 35, in generate_coco_dataset
    generate_coco_dataset_sub(args, 'train', 'A', args.cat1)
  File "/home/caocao/instagan-master/datasets/generate_coco_dataset.py", line 77, in generate_coco_dataset_sub
    seg_union[seg_union > 1] = 1  # remove duplicated parts
TypeError: 'int' object does not support item assignment
trainA:   0%|          | 46/118287 [00:06<4:25:51,  7.41it/s]

**Comment by sangwoomo** [comment]
Thanks! Frankly speaking, there was no problem when I tested the code (in ubuntu 16.04), but I guess there are some incompatibilities.
Nevertheless, I removed seg_union part, since it is deprecated and never used more.
Please check our updated code! (or simply remove seg_union part in your computer :))

**Comment by c1a1o1** [comment]
Thank you very much!
