### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by ghost** [sangwoomo/instagan#35]
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    opt = TestOptions().parse()
  File "/content/options/base_options.py", line 103, in parse
    opt = self.gather_options()
  File "/content/options/base_options.py", line 68, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/content/models/__init__.py", line 30, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/content/models/__init__.py", line 10, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.instagan_model'

**Comment by sangwoomo** [comment]
Hi, it seems that there is an error in python path.
See https://docs.python.org/3/tutorial/modules.html#packages for details!
