### ISSUE TITLE
OSError: could not read bytes

### ISSUE THREAD

**Issue by NguyenTriTrinh** [sangwoomo/instagan#43]
hello,when i run the python  ./datasets/generate_ccp_dataset.py, i got some errors
`trainA:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 989/1004 [00:31<00:00, 19.93it/s]Traceback (most recent call last):
  File "./datasets/generate_ccp_dataset.py", line 92, in <module>
    main()
  File "./datasets/generate_ccp_dataset.py", line 12, in main
    generate_ccp_dataset(args)
  File "./datasets/generate_ccp_dataset.py", line 36, in generate_ccp_dataset
    generate_ccp_dataset_train(args, 'A', args.cat1)
  File "./datasets/generate_ccp_dataset.py", line 52, in generate_ccp_dataset_train
    ann = sio.loadmat(str(args.pix_ann_root / '{}.mat'.format(ann_id)))['groundtruth']
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 208, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio5.py", line 272, in get_variables
    hdr, next_position = self.read_var_header()
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio5.py", line 217, in read_var_header
    mdtype, byte_count = self._file_reader.read_full_tag()
  File "mio5_utils.pyx", line 548, in scipy.io.matlab.mio5_utils.VarReader5.read_full_tag
  File "mio5_utils.pyx", line 556, in scipy.io.matlab.mio5_utils.VarReader5.cread_full_tag
  File "streams.pyx", line 86, in scipy.io.matlab.streams.GenericStream.read_into
OSError: could not read bytes
trainA: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 999/1004 [00:31<00:00, 32.07it/s]`
is there anything mistake about the datasets? thanku!

**Comment by NguyenTriTrinh** [comment]
i finished it by update the ccp datasets
