### ISSUE TITLE
dataloader is broken

### ISSUE THREAD

**Issue by syu-tan** [sangwoomo/instagan#46]
i try to do test `train.py` by jeans2skirt_ccp dataset.
but, mask image can't change tensor or, normalize 
this error 
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    for i, data in enumerate(dataset):
  File "/home/s-yasui/src/instagan/data/__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s-yasui/src/instagan/data/unaligned_seg_dataset.py", line 71, in __getitem__
    A_segs = self.read_segs(A_seg_path, seed)
  File "/home/s-yasui/src/instagan/data/unaligned_seg_dataset.py", line 42, in read_segs
    seg = self.fixed_transform(seg, seed)
  File "/home/s-yasui/src/instagan/data/unaligned_seg_dataset.py", line 34, in fixed_transform
    return self.transform(image)
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/s-yasui/anaconda3/envs/ai/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 300, 200] doesn't match the broadcast shape [3, 300, 200]

please help , thank you

**Comment by sangwoomo** [comment]
Hi, the code is based on old libraries (e.g., PyTorch 0.4), hence there is some compatibility problem.
I think Issue https://github.com/sangwoomo/instagan/issues/36 would help.
