### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1) must match the existing size (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#9]
Hi！I use your pre-trained model and follow the README.md，here follows the output:
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 26.815 M
[Network G_B] Total number of parameters : 26.815 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    for i, data in enumerate(dataset):
  File "D:\MINE\Papers\instagan-master\data\__init__.py", line 72, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\unaligned_seg_dataset.py", line 71, in __getitem__
    A_segs = self.read_segs(A_seg_path, seed)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\unaligned_seg_dataset.py", line 42, in read_segs
    seg = self.fixed_transform(seg, seed)
  File "D:\MINE\STUDY in SYSU\SmartLLV\Papers\instagan-master\data\unaligned_seg_dataset.py", line 34, in fixed_transform
    return self.transform(image)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torchvision\transforms\transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "D:\devcool\Anaconda2\envs\python36\lib\site-packages\torchvision\transforms\functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The expanded size of the tensor (1) must match the existing size (3) at non-singleton dimension 0

**Comment by sangwoomo** [comment]
Hi, which version of PyTorch are you using?
I searched Google, and found some similar issues, e.g., https://github.com/marvis/pytorch-yolo2/issues/84, https://github.com/marvis/pytorch-yolo3/issues/15, and https://github.com/Microsoft/singleshotpose/issues/10.
It seems that there are some incompatibilities along different PyTorch versions (I may fix it later). I used Python 3 and PyTorch 0.4 for my experiments.

**Comment by hjwang-824** [comment]
Thanks, I used Python3.6,  PyTorch 0.4.0 and CUDA 9.0

**Comment by sangwoomo** [comment]
Are you using the sample dataset or your own dataset?

**Comment by hjwang-824** [comment]
the sample dataset pans2skirt_mhp

**Comment by sangwoomo** [comment]
It seems that there is an incompatibility in torchvision. Can you check which version are you using? You can check it with the following code (I'm using 0.2.1).
```
import torchvision
print(torchvision.__version__)
```
The problematic part seems to be line 56-57 of https://github.com/sangwoomo/instagan/blob/master/data/base_dataset.py.

**Comment by hjwang-824** [comment]
I used torchvision 0.2.2post3， then I will try again to see whether is this reason. Thanks！

**Comment by hjwang-824** [comment]
It works，thank you so much！
